POST http://localhost:8080/patients
Content-Type: application/json

{
	"name":"piyush",
	"email":"sab98@gmail.com",
	"address":"gandhi nagar",
	"dateofbirth":"12/1/2002",
	"registeredDate":"4/4/2025"
}